// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.7
// source: internal/grpc/calc.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expression    string                 `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcRequest) Reset() {
	*x = CalcRequest{}
	mi := &file_internal_grpc_calc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcRequest) ProtoMessage() {}

func (x *CalcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_calc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcRequest.ProtoReflect.Descriptor instead.
func (*CalcRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_calc_proto_rawDescGZIP(), []int{0}
}

func (x *CalcRequest) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

type CalcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float64                `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcResponse) Reset() {
	*x = CalcResponse{}
	mi := &file_internal_grpc_calc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcResponse) ProtoMessage() {}

func (x *CalcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_calc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcResponse.ProtoReflect.Descriptor instead.
func (*CalcResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_calc_proto_rawDescGZIP(), []int{1}
}

func (x *CalcResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *CalcResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_grpc_calc_proto protoreflect.FileDescriptor

const file_internal_grpc_calc_proto_rawDesc = "" +
	"\n" +
	"\x18internal/grpc/calc.proto\"-\n" +
	"\vCalcRequest\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\tR\n" +
	"expression\"<\n" +
	"\fCalcResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x01R\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error27\n" +
	"\vCalcService\x12(\n" +
	"\tCalculate\x12\f.CalcRequest\x1a\r.CalcResponseB\x1fZ\x1dDistributedCalc/internal/grpcb\x06proto3"

var (
	file_internal_grpc_calc_proto_rawDescOnce sync.Once
	file_internal_grpc_calc_proto_rawDescData []byte
)

func file_internal_grpc_calc_proto_rawDescGZIP() []byte {
	file_internal_grpc_calc_proto_rawDescOnce.Do(func() {
		file_internal_grpc_calc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_calc_proto_rawDesc), len(file_internal_grpc_calc_proto_rawDesc)))
	})
	return file_internal_grpc_calc_proto_rawDescData
}

var file_internal_grpc_calc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_grpc_calc_proto_goTypes = []any{
	(*CalcRequest)(nil),  // 0: CalcRequest
	(*CalcResponse)(nil), // 1: CalcResponse
}
var file_internal_grpc_calc_proto_depIdxs = []int32{
	0, // 0: CalcService.Calculate:input_type -> CalcRequest
	1, // 1: CalcService.Calculate:output_type -> CalcResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpc_calc_proto_init() }
func file_internal_grpc_calc_proto_init() {
	if File_internal_grpc_calc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_calc_proto_rawDesc), len(file_internal_grpc_calc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_calc_proto_goTypes,
		DependencyIndexes: file_internal_grpc_calc_proto_depIdxs,
		MessageInfos:      file_internal_grpc_calc_proto_msgTypes,
	}.Build()
	File_internal_grpc_calc_proto = out.File
	file_internal_grpc_calc_proto_goTypes = nil
	file_internal_grpc_calc_proto_depIdxs = nil
}
